tables updated functions linked together
pcrontab first version finished

diff --git a/pcrontab b/pcrontab
--- a/pcrontab
+++ b/pcrontab
@@ -7,6 +7,7 @@ display_usage() {
 
 
 parse_file() {
+    log_file="/var/log/pcron"
     #checking the file is existing and readable
     if [ ! -r "$1" ]; then
         echo "le fichier n'est pas lisible ou n'existe pas" 
@@ -15,22 +16,24 @@ parse_file() {
         #define a boolean to be true if the file is correct and false otherwise
         correct=0
         #define the numbers that are alowed for each part of the schedule
-        type0='[0-3]'
-        type1='[1-5]?[0-9]'
-        type2='1?[0-9]$|^2[0-3]'
-        type3='[1-2]?[0-9]$|^3[0-1]'
-        type4='[1-9]$|^1[0-2]'
-        type5='[0-6]'
+        types=(
+  	    '[0-3]'
+  	    '[1-5]?[0-9]'
+  	    '1?[0-9]$|^2[0-3]'
+  	    '[1-2]?[0-9]$|^3[0-1]'
+    	'[1-9]$|^1[0-2]'
+    	'[0-6]'
+	)
         line=1 #keep track of the lines
         # Check each lines, not-commented lines should be checked
         while read ligne
         do
             if ! echo "$ligne" | grep -q '^#' ; then
                 field=0 #keep track of the field number
-                set -f
-                for mot in "$ligne"
+		        set -f #désactive le globbing pour pouvoir lire les * comme des caractères normaux
+                for mot in $ligne
                 do
-                set +f
+		            set +f
                     if [ "$field" -gt 5 ]; then 
                         break
                     fi
@@ -42,9 +45,9 @@ parse_file() {
                         else
                             last="$(echo "$mot" | cut -d"~" -f1 | cut -d"-" -f2)"
                         fi
-                        if [ "$first" -ge "$last" ]; then 
+                        if [ "$first" -ge "$last" ]; then
                             correct=1
-                            echo "l'intervalle du champ $((field+1)) de la ligne $line est incorrect : la première valeur est plus grande que la seconde"
+                            echo "l'intervalle du champ $((field+1)) de la ligne $line est incorrect : la première valeur est plus grande que la seconde" 2>> "$log_file"
                             break
                         else 
                             for i in $(seq 2 "$(echo "$mot" | awk 'BEGIN {FS="~"} {print NF}')")
@@ -52,18 +55,17 @@ parse_file() {
                                 bannedValue=$(echo "$mot" | cut -d"~" -f"$i")
                                 if [ "$bannedValue" -lt "$first" ] || [ "$bannedValue" -gt "$last" ]; then
                                     correct=2
-                                    echo "la valeur bannie $bannedValue de l''intervalle du champ $((field+1)) de la ligne $line doit être comprise dans l'intervalle inital"
+                                    echo "la valeur bannie $bannedValue de l'intervalle du champ $((field+1)) de la ligne $line doit être comprise dans l'intervalle inital" 2>> "$log_file"
                                     break
                                 fi
                             done
                         fi
                     fi
-                    #concatenate into one type that will change value for every iteration
-                    typeField="type""$field"
-                    type=$(eval echo \$"$typeField")
+                    #calls the types value that fits with the field number
+                    type=${types[$field]}
                     if ! echo "$mot" | grep -E -q "^$type(:$type)*$|^$type-$type(\~$type)*$|^\*\/$type$|^\*$" ; then
                         correct=3
-                        echo "la valeur de $mot est incorrecte sur le champ $((field+1)) de la ligne $line"
+                        echo "la valeur $mot est incorrecte sur le champ $((field+1)) de la ligne $line" 2>> "$log_file"
                     fi
                     ((field++))
                 done
@@ -73,6 +75,7 @@ parse_file() {
         return $correct
     fi
 }
+
 
 file_usage="# Edit this file to introduce tasks to be run by pcron.
 #
@@ -131,15 +134,15 @@ case $action in
         fi
 
         vi "$temp_file"
-        #while $(( parse_file "$temp_file" )); do
-        #	echo "There is an error in $temp_file, do you wish to fix it (y/n) ?"
-        #	read answer
-        #	if [ answer == "n" ]; then
-        #		exit 1
-        #	elif [ answer == "y" ]; then
-        #		vi "$temp_file"
-        #	fi
-        #done
+        until parse_file "$temp_file" ; do
+        	echo "There is an error in $temp_file, do you wish to fix it (y/n) ?"
+        	read answer
+        	if [ "$answer" == "n" ]; then
+        		exit 1
+        	elif [ "$answer" == "y" ]; then
+        		vi "$temp_file"
+        	fi
+        done
         mkdir -p "$pcron_dir"
         cp "$temp_file" "$pcron_user_file"
         rm "$temp_file"
